site_name: Stark & Wayne Codex
pages:
  - Getting Started:
    - Introduction: index.md
    - Network Design: network.md
    - Conventions: conventions.md
  - Amazon Web Services:
    - Jumpbox Setup: aws/jumpbox.md
  - Google Cloud Platform:
    - Introduction: gcp/intro.md
  - Microsoft Azure:
    - Introduction: azure/intro.md
  - OpenStack:
    - Introduction: openstack/intro.md
  - VMWare vSphere:
    - Introduction: vsphere/intro.md

theme:
  name: 'material'
  custom_dir: 'theme-overrides'
  palette:
    primary: 'indigo'
  feature:
    tabs: true

  logo: 'images/favicon/favicon-64.png'

  font:
    text: 'Bitter' # https://fonts.google.com/specimen/Bitter
    code: 'Ubuntu Mono'

# http://www.mkdocs.org/user-guide/configuration/#site_dir
site_dir: site/codex

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.critic
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.superfences
  - toc(permalink=true)

repo_name: 'help fix codex'
repo_url: 'https://github.com/starkandwayne/codex'
edit_uri: edit/master/docs/
extra_css: [print.css]
google_analytics: ['UA-50822525-5', 'starkandwayne.com/codex']
