site_name: Stark & Wayne Codex
pages:
  - Start:
    - Introduction: index.md
    - Overview: start/overview.md
    - Network Design: start/network.md
    - Conventions: start/conventions.md
  - Prepare Infrastructure:
    - Options: prepare-infrastructure/options.md
    - Amazon Web Services: prepare-infrastructure/prepare-aws.md
    - Google Cloud Platform: prepare-infrastructure/prepare-gcp.md
    - Microsoft Azure: prepare-infrastructure/prepare-azure.md
    - OpenStack: prepare-infrastructure/prepare-openstack.md
    - VMWare vSphere: prepare-infrastructure/prepare-vsphere.md
  - Terraform:
    - Setup: terraform/setup.md
    - Jumpbox: terraform/jumpbox.md

theme:
  name: 'material'
  custom_dir: 'theme-overrides'
  palette:
    primary: 'indigo'
  feature:
    tabs: true

  logo: 'images/favicon/favicon-64.png'

  font:
    text: 'Bitter' # https://fonts.google.com/specimen/Bitter
    code: 'Ubuntu Mono'

# http://www.mkdocs.org/user-guide/configuration/#site_dir
site_dir: site/codex

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.critic
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.superfences
  - toc(permalink=true)

repo_name: 'help fix codex'
repo_url: 'https://github.com/starkandwayne/codex'
edit_uri: edit/master/docs/
extra_css: [print.css]
google_analytics: ['UA-50822525-5', 'starkandwayne.com/codex']
