meta:
  name:    codex
  # fly -t ohio-sw login -c https://ci-ohio.starkandwayne.com -n starkandwayne
  target:  ohio-sw
  url:     https://ci-ohio.starkandwayne.com

  cf:
    uri: https://api.run.pivotal.io
    organization: starkandwayne
    space-production: codex
    username: ((!pws-cf-username))
    password: ((!pws-cf-password))

  github:
    owner: starkandwayne
    repo: codex
    branch: master
    private_key:  ((!github-private-key))
    access_token: ((!github-access-token))
